tasks:
  - init: |
      npm install
    command: |
      echo "✨ Welcome to the Weather Dashboard Demo!"
      echo "🚀 Run these commands to start:"
      echo "npm start"

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
