apiVersion: v1
kind: Service
metadata:
  name: ml-inference-api
  namespace: ml-inference
  labels:
    app: ml-inference-api
spec:
  type: ClusterIP
  selector:
    app: ml-inference-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
